/* eslint-disable react/prop-types */
// import localFont from 'next/font/local'
import './globals.css'
import { storyblokInit, apiPlugin } from '@storyblok/react/rsc'
import StoryblokProvider from '@/components/StoryblokProvider'
import React from 'react'
import Link from 'next/link'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const cachedFetch = (input, init) => {
  return fetch(input, {
    ...init,
    // eslint-disable-next-line no-undef
    cache: process.env.NODE_ENV === 'development' ? 'no-store' : 'force-cache',
    // cache: 'no-store',
  })
}

storyblokInit({
  // eslint-disable-next-line no-undef
  accessToken: process.env.storyblokApiToken,
  use: [apiPlugin],
  apiOptions: {
    fetch: cachedFetch,
  },
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body className={`${inter.className} bg-blue-50`}>
          <header>
            <nav className="container mx-auto px-4 w-full py-8 flex justify-between">
              <Link href="/">Home</Link>
              <Link href="/tours">Tours</Link>
            </nav>
          </header>
          {children}
        </body>
      </html>
    </StoryblokProvider>
  )
}
