/* eslint-disable react/prop-types */
import localFont from 'next/font/local'
import './globals.css'
import { storyblokInit, apiPlugin } from '@storyblok/react/rsc'
import StoryblokProvider from '@/components/StoryblokProvider'
import React from 'react'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

const cachedFetch = (input, init) => {
  return fetch(input, {
    ...init,
    cache: 'no-store',
  })
}

storyblokInit({
  // eslint-disable-next-line no-undef
  accessToken: process.env.storyblokApiToken,
  use: [apiPlugin],
  apiOptions: {
    fetch: cachedFetch,
  },
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div> Layout</div>
          {children}
        </body>
      </html>
    </StoryblokProvider>
  )
}
